name: Update plugin repo

on:
  repository_dispatch:
    types: [plugin_zip_generated]

jobs:
  update-repo:
    runs-on: ubuntu-latest

    env:
      PLUGIN_ID: com.github.qvvonk.funpayhub.exec_plugin
      PLUGIN_URL: ${{ github.event.client_payload.url }}

    steps:

      - name: Checkout plugin repo
        uses: actions/checkout@v4

      - name: Download plugin.zip
        run: |
          echo $PLUGIN_URL
          curl -L -o plugin.zip $PLUGIN_URL

      - name: Calculate SHA256
        id: hash
        run: |
          HASH=$(sha256sum plugin.zip | cut -d ' ' -f1)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Read manifest.json
        id: manifest
        run: |
          VERSION=$(jq -r '.plugin_version' manifest.json)
          APP_VERSION=$(jq -r '.app_version' manifest.json)

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Clone plugins repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/funpayhub/fph_plugins_repo.git

      - name: Update repo JSON
        run: |
          cd fph_plugins_repo

          python update_repo.py \
            "${{ env.PLUGIN_ID }}" \
            "${{ steps.manifest.outputs.version }}" \
            "${{ steps.manifest.outputs.app_version }}" \
            "${{ steps.hash.outputs.hash }}" \
            "$PLUGIN_URL"

      - name: Commit and push
        run: |
          cd fph_plugins_repo

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add com.github.funpayhub.repo.json
          git commit -m "Add ${{ env.PLUGIN_ID }} ${{ steps.manifest.outputs.version }}"
          git push